# Generated by Django 5.2.4 on 2025-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='way',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('IN_OUT', 'In/Out')], max_length=10),
        ),
    ]
